apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  values:
    ingress:
      main:
        enabled: true
        hosts:
        - host: homeassist.samsonnguyen.ca
          paths:
            - path: /
              pathType: Prefix
        annotations:
          kubernetes.io/ingress.class: traefik
          cert-manager.io/cluster-issuer: letsencrypt-prod
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.tls: "true"
        tls:
          - secretName: homeassist-samsonnguyen-ca-tls
            hosts:
              - homeassist.samsonnguyen.ca
    prometheus:
      serviceMonitor:
        enabled: true
        bearerTokenSecret:
          name: prometheus-access-token
          key: access_token
    podAnnotations:
      backup.velero.io/backup-volumes: config
    mariadb:
      podAnnotations:
        backup.velero.io/backup-volumes: data
