apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
resources:
  - pv.yaml
  - ../../base/home-assistant
patchesStrategicMerge:
  - home-assistant-values.yaml
# patches:
#   - target:
#       kind: IngressRoute
#       name: home-assistant-ingress
#       namespace: home-assistant
#     patch: |-
#       - op: replace
#         path: /spec/routes/0/match
#         value: Host(`homeassist.samsonnguyen.ca`)
