apiVersion: v1
kind: PersistentVolume
metadata:
  name: home-assistant-config
  labels:
    app: homeassistant
spec:
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage:  10Gi
  nfs:
    path: /mnt/storage_1/k8s/manual/home-assistant/home-assistant-config
    server: freenas-int.samsonnguyen.ca
  volumeMode: Filesystem
