apiVersion: apps/v1
kind: Deployment
metadata:
  name: rtsptoweb
  namespace: rtsptoweb
spec:
  selector:
    matchLabels:
      app: rtsptoweb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: rtsptoweb
    spec:
      containers:
      - image: ghcr.io/deepch/rtsptoweb:latest
        volumeMounts:
        - mountPath: /config
          name: rtsptoweb
          readOnly: false
        name: rtsptoweb
        resources:
         requests:
           cpu: 1
           memory: 100Mi
         limits:
           cpu: 2
           memory: 2.5Gi
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - kube-worker2
      hostNetwork: true
      volumes:
      - name: rtsptoweb
        secret:
          secretName: rtsptoweb
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
