apiVersion: v1
kind: Service
metadata:
  name: rtsptoweb-udp
  namespace: rtsptoweb
  annotations:
    metallb.universe.tf/allow-shared-ip: "true"
spec:
  loadBalancerIP: 10.0.11.5
  ports:
  - name: rtc1
    port: 20052
    targetPort: 20052
    protocol: UDP
  - name: rtc2
    port: 20053
    targetPort: 20053
    protocol: UDP
  - name: rtc3
    port: 20054
    targetPort: 20054
    protocol: UDP
  - name: rtc4
    port: 20055
    targetPort: 20055
    protocol: UDP
  - name: rtc5
    port: 20056
    targetPort: 20056
    protocol: UDP
  - name: rtc6
    port: 20057
    targetPort: 20057
    protocol: UDP
  - name: rtc8
    port: 20058
    targetPort: 20058
    protocol: UDP
  selector:
    app: rtsptoweb
  sessionAffinity: None
  type: LoadBalancer
