apiVersion: v1
kind: Service
metadata:
  name: graphite-tcp
  namespace: graphite
spec:
  type: LoadBalancer
  ports:
    - name: graphite-pickle
      port: 2004
      protocol: TCP
    - name: graphite-plain
      port: 2003
      protocol: TCP
    - name: graphite-gui
      port: 8080
      protocol: TCP
    - name: aggregate-plain
      port: 2023
      protocol: TCP
    - name: aggregate-pickl
      port: 2024
      protocol: TCP
    - name: statsd
      port: 8125
      protocol: TCP
    - name: statsd-admin
      port: 8126
      protocol: TCP
  selector:
    app.kubernetes.io/name: graphite
    app.kubernetes.io/instance: graphite