apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kubernetes-replicator
spec:
  releaseName: kubernetes-replicator
  chart:
    spec:
      chart: kubernetes-replicator
      version: ~2.7
      sourceRef:
        kind: HelmRepository
        name: mittwald
        namespace: flux-system
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
