apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: velero
spec:
  releaseName: velero
  chart:
    spec:
      chart: velero
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu
        namespace: flux-system
  interval: 1h0m0s
  values:
    credentials:
      existingSecret: b2-credentials
    configuration:
      provider: aws
      backupStorageLocation:
        name: backblaze-backups
        bucket: samsonnguyen-homelab
        config:
          s3Url: https://s3.us-west-001.backblazeb2.com
          region: us-west-001
      volumeSnapshotLocation:
        name: backblaze-snapshots
        config:
          s3Url: https://s3.us-west-001.backblazeb2.com
          region: us-west-001
    deployRestic: true