apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: huginn
  namespace: huginn
spec:
  values:
    ingress:
      enabled: true
      hosts:
      - host: huginn.samsonnguyen.ca
        paths:
          - path: /
            pathType: Prefix
      annotations:
        kubernetes.io/ingress.class: traefik
        cert-manager.io/cluster-issuer: letsencrypt-prod
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
      tls:
        - secretName: huginn-samsonnguyen-ca-tls
          hosts:
            - huginn.samsonnguyen.ca
    mysql:
      primary:
        persistence:
          storageClass: openebs-jiva-default