apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: unifi-poller
resources:
  - ../../base/unifi-poller
configMapGenerator:
- name: unifi-poller
  files:
    - unifi-poller.conf
