apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflare-ddns
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-homelab-cloudflare-ddns
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cloudflare-ddns
        workload.user.cattle.io/workloadselector: deployment-homelab-cloudflare-ddns
    spec:
      containers:
      - env:
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: cloudflare-ddns
              key: API_KEY
        - name: ZONE
          valueFrom:
            secretKeyRef:
              name: cloudflare-ddns
              key: ZONE
        - name: SUBDOMAIN
          valueFrom:
            secretKeyRef:
              name: cloudflare-ddns
              key: SUBDOMAIN
        image: oznu/cloudflare-ddns
        imagePullPolicy: Always
        name: cloudflare-ddns
      imagePullSecrets:
      - name: docker-hub
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
