apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - release.yaml
  - ../../ingress
patches:
  - target:
      kind: IngressRoute
      name: ingress
    patch: |-
      - op: replace
        path: /metadata/name
        value: sonarr-ingress
      - op: add
        path: /spec/routes/0/services/0
        value: { "name": "sonarr", "port": 8989, "namespace": "media" }