apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonarr
spec:
  releaseName: sonarr
  chart:
    spec:
      chart: sonarr
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  interval: 5m
  values:
    env:
      PUID: "1001"
      PGID: "1001"
      TZ: "America/Edmonton"
    persistence:
      config:
        enabled: true
        storageClass: freenas-iscsi-csi
        size: 15Gi
      media:
        enabled: true
        accessMode: ReadWriteOnce
        storageClass: ""
        size: 8Ti