apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sonarr
spec:
  releaseName: sonarr
  chart:
    spec:
      chart: sonarr
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  interval: 5m
  values:
    image:
      repository: lscr.io/linuxserver/sonarr
      tag: latest
      pullPolicy: Always
    env:
      TZ: "America/Edmonton"
      PUID: "1001"
      PGID: "1001"
    persistence:
      config:
        enabled: true
        storageClass: local-hostpath
        accessMode: ReadWriteOnce
        type: pvc
        size: 15Gi
      shared:
        enabled: true
        type: pvc
        existingClaim: sonarr-shared
