apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: default-samsonnguyen-ca
  namespace: default
spec:
  secretName: default-samsonnguyen-ca
  secretTemplate:
    annotations:
      replicator.v1.mittwald.de/replicate-to-matching: >
        replicator.v1.mittwald.de/secret=default-samsonnguyen-ca
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - samsonnguyen.ca
  - "*.samsonnguyen.ca"