apiVersion: v1
kind: Secret
metadata:
  name: default-samsonnguyen-ca
  namespace: default
  annotations:
    replicator.v1.mittwald.de/replicate-to: ".*"
type: kubernetes.io/tls
data:
  tls.key: ""
  tls.crt: ""