apiVersion: v1
kind: Secret
metadata:
  name: wildcard-samsonnguyen-ca
  namespace: defaultClass
  annotations:
    replicator.v1.mittwald.de/replication-allowed: "true"
    replicator.v1.mittwald.de/replication-allowed-namespaces: "*"
type: kubernetes.io/tls
data:
  tls.key: ""
  tls.crt: ""