apiVersion: apps/v1
kind: Deployment
metadata:
  name: chevereto
  namespace: chevereto
spec:
  selector:
    matchLabels:
      app: chevereto
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: chevereto
    spec:
      containers:
      - env:
        - name: CHEVERETO_DEBUG_LEVEL
          value: '3'
        - name: CHEVERETO_DB_HOST
          value: mariadb
        - name: CHEVERETO_DB_NAME
          value: chevereto
        - name: CHEVERETO_DB_PASS
          valueFrom:
            secretKeyRef:
              name: chevereto-mariadb
              key: mariadb-password
        - name: CHEVERETO_DB_TABLE_PREFIX
          value: chv_
        - name: CHEVERETO_DB_USER
          value: chevereto
        image: ghcr.io/chevereto/chevereto:latest
        imagePullPolicy: Always
        name: chevereto
        resources:
        #  requests:
        #    cpu: 2
        #    memory: 2.5Gi
        #    ephemeral-storage: 50M
        #  limits: 
        #    cpu: 2
        #    memory: 2.5Gi
        #    ephemeral-storage: 50M
        volumeMounts:
        - mountPath: /var/www/html/images
          name: chevereto-images
          subPath: images
        - name: php-ini
          mountPath: /usr/local/etc/php/php.ini
          subPath: php.ini
          readOnly: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: chevereto-images
        persistentVolumeClaim:
          claimName: chevereto
      - name: php-ini
        configMap:
          name: chevereto-php-ini
