apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chevereto
  namespace: chevereto
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: ""
