---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingress
  namespace: prometheus
spec:
  entryPoints:
    - websecure
  routes:
    - match: 
      kind: Rule
      services:
      - name: kube-prometheus-stack-grafana
        port: 80
      middlewares:
      - name: basic-auth
        namespace: traefik
      - name: redirect-scheme
        namespace: traefik
  tls:
    secretName: wildcard-samsonnguyen-ca
