---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingress
spec:
  entryPoints:
    - websecure
  routes:
    - match:
      kind: Rule
      services: []
      middlewares:
      - name: sso
        namespace: traefik
      - name: redirect-scheme
        namespace: traefik
  tls:
    secretName: wildcard-samsonnguyen-ca
    domains:
      - main: samsonnguyen.ca
