---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: huginn
  namespace: huginn
spec:
  chart:
    spec:
      chart: huginn
      sourceRef:
        kind: HelmRepository
        name: utkuozdemir
        namespace: flux-system
  interval: 1m0s
