apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: heimdall
  namespace: heimdall
spec:
  values:
    ingress:
      enabled: true
      hosts:
      - host: home.samsonnguyen.ca
        paths:
          - path: /
            pathType: Prefix
      annotations:
        kubernetes.io/ingress.class: traefik
        cert-manager.io/cluster-issuer: letsencrypt-prod
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
        traefik.ingress.kubernetes.io/router.middlewares: sso@treafik
      tls:
        - secretName: home-samsonnguyen-ca-tls
          hosts:
            - home.samsonnguyen.ca
