apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - release.yaml
  - pvc-tv.yml
  - pvc.yml
  - ../../ingress
patches:
  - target:
      kind: IngressRoute
      name: ingress
    patch: |-
      - op: replace
        path: /metadata/name
        value: jellyfin-ingress
      - op: add
        path: /spec/routes/0/services/0
        value: { "name": "jellyfin", "port": "http", "namespace": "media" }
