apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-shared-tv
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 8Ti
  volumeMode: Filesystem
  volumeName: jellyfin-shared-tv
