---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      # -- Version of the app-template helm chart
      # this example is not automatically updated, so be sure to use the latest chart version
      version: 1.5.1
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    image:
      # -- image repository
      repository: jellyfin/jellyfin
      # -- image pull policy
      pullPolicy: IfNotPresent
      # -- image tag
      # this example is not automatically updated, so be sure to use the latest image
      tag: latest

    strategy:
      type: Recreate

    # -- environment variables.
    # See [image docs](https://github.com/dani-garcia/vaultwarden/blob/main/.env.template) for more details.
    env:
      # -- Config dir
      DATA_FOLDER: "config"
      JELLYFIN_PublishedServerUrl: "https://jellyfin.samsonnguyen.ca"

    resources:
      requests:
        # Hardware acceleration using an Intel iGPU w/ QuickSync and
        # using intel-gpu-plugin (https://github.com/intel/intel-device-plugins-for-kubernetes)
        gpu.intel.com/i915: 1
        nvidia.com/gpu: 1
        cpu: 200m
        memory: 500Mi
      limits:
        # Hardware acceleration using an Intel iGPU w/ QuickSync and
        # using intel-gpu-plugin (https://github.com/intel/intel-device-plugins-for-kubernetes)
        gpu.intel.com/i915: 1
        nvidia.com/gpu: 1
        memory: "6Gi"

    # -- Configures service settings for the chart.
    service:
      main:
        externalTrafficPolicy: Local
        type: LoadBalancer
        ports:
          http:
            port: "8096"

    ingress:
      # -- Enable and configure ingress settings for the chart under this key.
      main:
        enabled: false
        hosts:
          - host: chart-example.local
            paths:
              - path: /
                pathType: Prefix
                service:
                  port: http

    # -- Configure persistence settings for the chart under this key.
    persistence:
      config:
        enabled: true
        type: pvc
        accessMode: ReadWriteOnce
        storageClass: local-hostpath
        size: 1Gi
        mountPath: /config
      shared:
        enabled: true
        type: pvc
        existingClaim: jellyfin-shared
      shared-tv:
        enabled: true
        type: pvc
        existingClaim: jellyfin-shared-tv