apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: democratic-csi
spec:
  releaseName: democratic-csi
  chart:
    spec:
      chart: democratic-csi
      version: "0.13.5"
      sourceRef:
        kind: HelmRepository
        name: democratic-csi
        namespace: flux-system
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
