apiVersion: v1
kind: PersistentVolume
metadata:
  finalizers:
  - kubernetes.io/pv-protection
  name: chevereto
  namespace: chevereto
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 100Gi
  nfs:
    path: /mnt/storage_1/k8s/chevereto
    server: freenas-int.samsonnguyen.ca
  storageClassName: ""
