apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
resources:
  - ../../base/chevereto
  - chevereto-pv.yaml
patches:
  - target:
      kind: IngressRoute
      name: chevereto-ingress
      namespace: chevereto
    patch: |-
      - op: replace
        path: /spec/routes/0/match
        value: Host(`photos.samsonnguyen.ca`)