apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - release.yaml
  - pvc.yml
  - ../../ingress
patches:
  - target:
      kind: IngressRoute
      name: ingress
    patch: |-
      - op: replace
        path: /metadata/name
        value: radarr-ingress
      - op: add
        path: /spec/routes/0/services/0
        value: {"name": "radarr", "port": 7878, "namespace": "media" }
