apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-shared
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 8Ti
  volumeMode: Filesystem
  volumeName: radarr-shared
