apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sealed-secrets
spec:
  releaseName: sealed-secrets
  chart:
    spec:
      chart: sealed-secrets
      version: ~2.1
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets
        namespace: flux-system
  interval: 1h0m0s