apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
spec:
  releaseName: metallb
  chart:
    spec:
      chart: metallb
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    configInline:
      peers:
      - peer-address: 10.0.10.1
        peer-asn: 64512
        my-asn: 64500
      address-pools:
      - name: default
        protocol: bgp
        addresses:
        - 10.0.11.0/24
        avoid-buggy-ips: true
    controller:
      prometheus:
        serviceMonitor:
          enabled: true