---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: invoiceninja
  namespace: invoiceninja
spec:
  chart:
    spec:
      chart: invoiceninja
      version: ~0.7.0
      sourceRef:
        kind: HelmRepository
        name: invoiceninja
        namespace: flux-system
  interval: 1m0s
  values:
    existingSecret: invoiceninja
    redis:
      auth:
        existingSecret: invoiceninja-redis
    mariadb:
      auth:
        existingSecret: invoiceninja-mariadb