apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: apaxy
  name: apaxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apaxy
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: apaxy
    spec:
      containers:
      - image: fusengine/apaxy
        imagePullPolicy: Always
        name: apaxy
        resources: {}
        ports:
          - containerPort: 80
        volumeMounts:
          - mountPath: /app/web/Movies
            name: movies-data
          - mountPath: /app/web/TV
            name: tv-data
      volumes:
        - name: movies-data
          nfs:
            path: /mnt/media
            server: kube-worker2.samsonnguyen.ca
        - name: tv-data
          nfs:
            path: "/mnt/media2"
            server: kube-worker2.samsonnguyen.ca
