apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/paperless
- paperless-consume-pv.yaml
- paperless-media-pv.yaml
- paperless-export-pv.yaml
patches:
- path: paperless-values.yaml
