apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
resources:
  - ../../base/paperless
  - paperless-consume-pv.yaml
  - paperless-media-pv.yaml
patchesStrategicMerge:
  - paperless-values.yaml
