apiVersion: v1
kind: PersistentVolume
metadata:
  finalizers:
  - kubernetes.io/pv-protection
  name: paperless-media
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 100Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: paperless-media
    namespace: paperless
  nfs:
    path: /mnt/storage_1/k8s/manual/paperless/paperless-media
    server: freenas-int.samsonnguyen.ca
  volumeMode: Filesystem
