apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: paperless
  namespace: paperless
spec:
  values:
    image:
      tag: 1.5.0
    env:
      PAPERLESS_CONSUMPTION_DIR: /usr/src/paperless/consume
      PAPERLESS_REDIS: "redis://paperless-redis-master:6379"
    redis:
      enabled: true
      global:
        storageClass: openebs-jiva
      replica:
        replicaCount: 1
    persistence:
      data:
        enabled: true
        storageClass: openebs-jiva
        accessMode: ReadWriteOnce
        size: 5Gi
      media:
        enabled: true
        existingClaim: paperless-media
      consume:
        enabled: true
        existingClaim: paperless-consume
    probes:
      liveness:
        enabled: true
        custom: true
        spec:
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
    ingress:
      main:
        enabled: true
        hosts:
        - host: docs.samsonnguyen.ca
          paths:
            - path: /
              pathType: Prefix
        annotations:
          kubernetes.io/ingress.class: traefik
          cert-manager.io/cluster-issuer: letsencrypt-prod
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.tls: "true"
          traefik.ingress.kubernetes.io/router.middlewares: traefik-sso@kubernetescrd
        tls:
          - secretName: docs-samsonnguyen-ca-tls
            hosts:
              - docs.samsonnguyen.ca
    podAnnotations:
      backup.velero.io/backup-volumes: data