apiVersion: v1
kind: PersistentVolume
metadata:
  name: paperless-export
  labels:
    app: paperless
spec:
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 1Gi
  nfs:
    path: /mnt/storage_1/k8s/manual/paperless/paperless-export
    server: freenas-int.samsonnguyen.ca
  volumeMode: Filesystem
