apiVersion: v1
kind: PersistentVolume
metadata:
  name: paperless-media
  labels:
    app: paperless
spec:
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 100Gi
  nfs:
    path: /mnt/storage_1/k8s/manual/paperless/paperless-media
    server: freenas-int.samsonnguyen.ca
  volumeMode: Filesystem
