apiVersion: v1
kind: PersistentVolume
metadata:
  finalizers:
  - kubernetes.io/pv-protection
  name: paperless-consume
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage:  10Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: paperless-consume
    namespace: paperless
  nfs:
    path: /mnt/storage_1/k8s/manual/paperless/paperless-consume
    server: freenas-int.samsonnguyen.ca
  volumeMode: Filesystem
