apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: paperless
  namespace: paperless
spec:
  values:
    env:
      PAPERLESS_CONSUMPTION_DIR: /usr/src/paperless/consume
    persistence:
      data:
        enabled: true
        storageClass: openebs-jiva
        accessMode: ReadWriteOnce
        size: 5Gi
      media:
        enabled: true
        existingClaim: paperless-media
      consume:
        enabled: true
        existingClaim: paperless-consume
    ingress:
      main:
        enabled: true
        hosts:
        - host: docs.samsonnguyen.ca
          paths:
            - path: /
              pathType: Prefix
        annotations:
          kubernetes.io/ingress.class: traefik
          cert-manager.io/cluster-issuer: letsencrypt-prod
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.tls: "true"
          traefik.ingress.kubernetes.io/router.middlewares: traefik-sso@kubernetescrd
        tls:
          - secretName: docs-samsonnguyen-ca-tls
            hosts:
              - docs.samsonnguyen.ca
    podAnnotations:
      backup.velero.io/backup-volumes: data