apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: paperless
  namespace: paperless
spec:
  values:
    env:
      PAPERLESS_CONSUMPTION_DIR: /usr/src/paperless/consume
      PAPERLESS_CONSUMER_POLLING: 10
      PAPERLESS_BIND_ADDR: "0.0.0.0"
    redis:
      enabled: true
      global:
        storageClass: openebs-jiva
      replica:
        replicaCount: 1
    persistence:
      data:
        enabled: true
        storageClass: openebs-jiva
        accessMode: ReadWriteOnce
        size: 5Gi
      media:
        enabled: true
        accessMode: ReadWriteMany
        type: pvc
        storageClass: ""
        size: 100Gi
        selector:
          matchLabels:
            app: paperless
      consume:
        enabled: true
        accessMode: ReadWriteMany
        type: pvc
        storageClass: ""
        size: 10Gi
        selector:
          matchLabels:
            app: paperless
      export:
        accessMode: ReadWriteOnce
        size: 1Gi
    ingress:
      main:
        enabled: true
        hosts:
        - host: docs.samsonnguyen.ca
          paths:
            - path: /
              pathType: Prefix
        annotations:
          kubernetes.io/ingress.class: traefik
          cert-manager.io/cluster-issuer: letsencrypt-prod
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.tls: "true"
          traefik.ingress.kubernetes.io/router.middlewares: traefik-sso@kubernetescrd
        tls:
          - secretName: docs-samsonnguyen-ca-tls
            hosts:
              - docs.samsonnguyen.ca
    podAnnotations:
      backup.velero.io/backup-volumes: data
