apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- pv.yaml
- ../../base/node-red
patches:
- path: ingressroute-patch.yaml
  target:
    kind: IngressRoute
    name: node-red-ingress
    namespace: node-red
- path: node-red-values.yaml
