apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - pv.yaml
  - ../../base/node-red
patchesStrategicMerge:
  - node-red-values.yaml
patches:
  - target:
      kind: IngressRoute
      name: node-red-ingress
      namespace: node-red
    path: ingressroute-patch.yaml
