apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: node-red
  namespace: node-red
spec:
  values:
    resources: 
      limits:
        cpu: 200m
        memory: 512Mi
      requests:
        cpu: 200m
        memory: 256Mi