apiVersion: v1
kind: PersistentVolume
metadata:
  name: node-red-config
  labels:
    app: nodered
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage:  10Gi
  nfs:
    path: /mnt/storage_1/k8s/manual/node-red/node-red-config
    server: freenas-int.samsonnguyen.ca
  volumeMode: Filesystem
