apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
namespace: node-red
resources:
  - namespace.yaml
  - release.yaml
  - ../ingress
patches:
  - target:
      kind: IngressRoute
      name: ingress
    patch: |-
      - op: replace
        path: /metadata/name
        value: node-red-ingress
  - target:
      kind: IngressRoute
      name: ingress
    path: ingress-patch.yaml