apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: node-red
  namespace: node-red
spec:
  releaseName: node-red
  chart:
    spec:
      chart: node-red
      version: ~9.0.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  values:
    image:
      repository: samsonnguyen/nodered-tuya-local
      tag: latest
    env:
      PUID: "1001"
      PGID: "1001"
      TZ: "America/Edmonton"
    persistence:
      data:
        enabled: true
        # emptyDir:
        #   enabled: false
        # storageClass: "-"
        # size: 15Gi
        existingClaim: "node-red-config"
    mariadb:
      enabled: true
      primary:
        persistence:
          enabled: true
          storageClass: freenas-iscsi-csi
    prometheus:
      serviceMonitor:
        enabled: true