apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: node-red
  namespace: node-red
spec:
  releaseName: node-red
  chart:
    spec:
      chart: node-red
      version: ~10.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  values:
    image:
      repository: samsonnguyen/nodered-tuya-local
      tag: latest
    env:
      PUID: "1001"
      PGID: "1001"
      TZ: "America/Edmonton"
    persistence:
      data:
        enabled: true
        accessMode: ReadWriteMany
        type: pvc
        storageClass: ""
        size: 10Gi
        selector:
          matchLabels:
            app: nodered
    mariadb:
      enabled: true
      primary:
        persistence:
          enabled: true
          storageClass: freenas-iscsi-csi
    prometheus:
      serviceMonitor:
        enabled: true
