apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openebs
spec:
  releaseName: openebs
  chart:
    spec:
      chart: openebs
      version: ~2.9.0
      sourceRef:
        kind: HelmRepository
        name: openebs
        namespace: flux-system
  interval: 1h0m0s
  values:
    jiva:
      replicas: 2