apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - release.yaml
  - ../../ingress
patches:
  - target:
      kind: IngressRoute
      name: ingress
    patch: |-
      - op: replace
        path: /metadata/name
        value: overseerr-ingress
      - op: add
        path: /spec/routes/0/services/0
        value: {"name": "overseerr", "port": 5055, "namespace": "media" }
