apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bazarr
spec:
  releaseName: bazarr
  chart:
    spec:
      chart: bazarr
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  interval: 5m
  values:
    env:
      TZ: "America/Edmonton"
    persistence:
      shared:
        enabled: true
        type: pvc
        existingClaim: bazarr-shared
      shared-tv:
        enabled: true
        type: pvc
        existingClaim: bazarr-shared-tv
      config:
        enabled: true
        accessMode: ReadWriteOnce
        storageClass: local-hostpath
        type: pvc
        size: 15Gi
