apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bazarr
spec:
  releaseName: bazarr
  chart:
    spec:
      chart: bazarr
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  interval: 5m
  values:
    env:
      TZ: "America/Edmonton"
    persistence:
      config:
        enabled: true
        storageClass: openebs-jiva
        size: 15Gi
      media:
        enabled: true
        accessMode: ReadWriteOnce
        storageClass: ""
        size: 8Ti