apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  values:
    image:
      tag: 21-apache
    livenessProbe:
      enabled: false
    readinessProbe:
      enabled: false
    persistence:
      enabled: true
      storageClass: freenas-iscsi-csi
      size: 500Gi
    metrics:
      enabled: true
    nextcloud:
      host: cloud.samsonnguyen.ca
      extraEnv:
        OVERWRITEPROTOCOL: https
    postgresql:
      enabled: true
      persistence:
        enabled: true
        storageClass: freenas-iscsi-csi
        size: 20Gi
    redis:
      enabled: true
      master:
        persistence:
          storageClass: freenas-iscsi-csi
      slave:
        persistence:
          storageClass: freenas-iscsi-csi
    cronjob:
      enabled: true
    internalDatabase:
      enabled: false
    externalDatabase:
      enabled: true
      host: nextcloud-postgresql
      type: postgresql
      username: nextcloud
      password: changeme
    ingress:
      enabled: false


