apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  values:
    persistence:
      enabled: true
      storageClass: freenas-iscsi-csi
      size: 500Gi
    metrics.enabled: true
    nextcloud:
      host: cloud.samsonnguyen.ca
    postgresql:
      enabled: true
      persistence:
        enabled: true
        storageClass: freenas-iscsi-csi
        size: 20Gi
    redis:
      enabled: true
      master:
        persistence:
          storageClass: freenas-iscsi-csi
      slave:
        persistence:
          storageClass: freenas-iscsi-csi
    cronjob:
      enabled: true
    internalDatabase:
      enabled: false
    externalDatabase:
      enabled: true
      host: nextcloud-postgresql
      type: postgresql
      username: postgres
      password: changeme
      # existingSecret:
      #   secretName: nextcloud-postgresql
      #   passwordKey: postgresql-password
      #   usernameKey: postgresql-user



