apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  values:
    image:
      tag: 21-apache
    livenessProbe:
      enabled: false
    readinessProbe:
      enabled: false
    persistence:
      enabled: true
      storageClass: freenas-iscsi-csi
      size: 500Gi
    metrics:
      enabled: true
      https: true
      timeout: 15
    nextcloud:
      host: cloud.samsonnguyen.ca
      extraEnv:
        - name: OVERWRITEPROTOCOL
          value: https
      existingSecret:
        secretName: nextcloud-users
    postgresql:
      enabled: true
      persistence:
        enabled: true
        storageClass: freenas-iscsi-csi
        size: 20Gi
    redis:
      enabled: true
      master:
        persistence:
          storageClass: freenas-iscsi-csi
      slave:
        persistence:
          storageClass: freenas-iscsi-csi
    cronjob:
      enabled: true
    internalDatabase:
      enabled: false
    externalDatabase:
      enabled: true
      host: nextcloud-postgresql
      type: postgresql
      username: nextcloud
      password: changeme
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: traefik
        cert-manager.io/cluster-issuer: letsencrypt-prod
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
        traefik.ingress.kubernetes.io/router.middlewares: nextcloud-nextcloud-redirectregex@kubernetescrd
      tls:
        - secretName: cloud-samsonnguyen-ca-tls
          hosts:
            - cloud.samsonnguyen.ca
