apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: prometheus
spec:
  chart:
    spec:
      version: ">=14.5.0"
  values:
    grafana:
      plugins:
        - grafana-piechart-panel
      ingress: 
        enabled: false
      persistence:
        enabled: true
        storageClassName: freenas-iscsi-csi
        size: 50Gi
      grafana.ini:
        server:
          root_url: https://grafana.samsonnguyen.ca
        auth.anonymous:
          enabled: true
          org_name: admin
          org_role: Admin
    prometheus:
      ingress:
        enabled: false
      prometheusSpec:
        serviceMonitorSelectorNilUsesHelmValues: false
        resources:
          requests:
            memory: 800Mi
            cpu: 400m
          limits:
            memory: 1200Mi
            cpu: 1500m
        retention: 10d
      additionalServiceMonitors:
        - name: nextcloud
          endpoints:
          - path: metrics
            port: metrics
          namespaceSelector:
            matchNames:
            - nextcloud
          podTargetLabels:
          - app.kubernetes.io/component=metrics
          selector:
            matchLabels:
              app.kubernetes.io/instance: nextcloud
        - name: pve2-metrics
          endpoints:
          - path: metrics
            port: metrics
          namespaceSelector:
            matchNames:
            - metrics
          selector:
            matchLabels:
              samsonnguyen.ca/host: pve2-int
        - name: traefik
          endpoints:
          - path: metrics
            port: traefik
          namespaceSelector:
            matchNames:
            - traefik
          selector:
            matchLabels:
              app.kubernetes.io/instance: traefik
        - name: unifi-poller
          endpoints:
          - path: metrics
            port: metrics-tcp
          namespaceSelector:
            matchNames:
            - unifi-poller
          selector:
            matchLabels:
              samsonnguyen.ca/instance: unifi-poller