apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: prometheus
spec:
  chart:
    spec:
      version: ">=14.5.0"

  values:
    grafana:
      ingress: false
      persistence:
        enabled: true
        storageClassName: freenas-nfs-csi
        size: 50Gi
      grafana.ini:
        server:
          root_url: https://grafana.samsonnguyen.ca
    prometheus:
      ingress:
        enabled: false
        hosts:
          - metrics.dev1.use1.immunet.com
        paths:
          - /*
        pathType: Prefix