apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  releaseName: nextcloud
  chart:
    spec:
      chart: nextcloud
      sourceRef:
        kind: HelmRepository
        name: nextcloud
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  values:
    persistence:
      enabled: true
      storageClass: org.democratic-csi.nfs
      size: 500Gi
    metrics.enabled: true