apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: prometheus
spec:
  chart:
    spec:
      version: ">=14.5.0"
  values:
    grafana:
      deploymentStrategy:
        type: Recreate
      plugins:
        - grafana-piechart-panel
      ingress: 
        enabled: false
      persistence:
        enabled: true
        storageClassName: freenas-iscsi-csi
        size: 50Gi
      grafana.ini:
        server:
          root_url: https://grafana.samsonnguyen.ca
        auth.anonymous:
          enabled: true
          org_name: admin
          org_role: Admin
        auth.ldap:
          enabled: true
          allow_sign_up: true
          config_file: /etc/grafana/ldap.toml
        smtp:
          enabled: true
          host: smtp.zoho.com
          from_address: donotreply@samsonnguyen.ca
          from_name: Grafana
      ldap:
        enabled: true
        existingSecret: kube-prometheus-stack-grafana
      smtp:
        existingSecret: kube-prometheus-stack-grafana-smtp
        userKey: username
        passwordKey: password
      podAnnotations:
        backup.velero.io/backup-volumes: storage
    prometheusOperator:
      image:
        repository: quay.io/prometheus-operator/prometheus-operator
        tag: v0.47.1
    prometheus:
      ingress:
        enabled: false
      prometheusSpec:
        serviceMonitorSelectorNilUsesHelmValues: false
        resources:
          requests:
            memory: 800Mi
            cpu: 400m
          limits:
            memory: 3Gi
            cpu: 1500m
        retention: 10d
      additionalServiceMonitors:
        - name: nextcloud
          endpoints:
          - path: metrics
            port: metrics
          namespaceSelector:
            matchNames:
            - nextcloud
          podTargetLabels:
          - app.kubernetes.io/component=metrics
          selector:
            matchLabels:
              app.kubernetes.io/instance: nextcloud
        - name: pve2-metrics
          endpoints:
          - path: metrics
            port: metrics
          namespaceSelector:
            matchNames:
            - metrics
          selector:
            matchLabels:
              samsonnguyen.ca/host: pve2-int
        - name: traefik
          endpoints:
          - path: metrics
            port: traefik
          namespaceSelector:
            matchNames:
            - traefik
          selector:
            matchLabels:
              app.kubernetes.io/instance: traefik
        - name: unifi-poller
          endpoints:
          - path: metrics
            port: metrics-tcp
          namespaceSelector:
            matchNames:
            - unifi-poller
          selector:
            matchLabels:
              samsonnguyen.ca/instance: unifi-poller
        - name: kube-worker2-metrics
          endpoints:
          - path: metrics
            port: metrics
          namespaceSelector:
            matchNames:
            - metrics
          selector:
            matchLabels:
              samsonnguyen.ca/host: kube-worker2