apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: intel-gpu-plugin
spec:
  releaseName: intel-gpu-plugin
  chart:
    spec:
      chart: intel-gpu-plugin
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  interval: 1h0m0s
  values:
    sharedDevNum: 2
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: feature.node.kubernetes.io/pci-0300_8086.present
                  operator: In
                  values:
                    - "true"