---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kubevious
  namespace: kubevious
spec:
  chart:
    spec:
      chart: kubevious
      version: ~0.9.0
      sourceRef:
        kind: HelmRepository
        name: kubevious
        namespace: flux-system
  interval: 1m0s
