apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: paperless
spec:
  releaseName: paperless
  chart:
    spec:
      chart: paperless
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  interval: 5m
  values:
    redis:
      enabled: true
    env:
      PAPERLESS_REDIS: "redis://localhost:6379"
