apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: paperless
spec:
  releaseName: paperless
  chartRef:
    kind: OCIRepository
    name: paperless-ngx
    namespace: flux-system
  interval: 5m
