apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager
resources:
  - namespace.yaml
  - release.yaml
  - sealed-cloudflare-api-token-secret.yaml
  # - letsencrypt-staging.yml
  # - letsencrypt-prod.yml