apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
namespace: media
resources:
  - namespace.yaml
  - radarr
  - sonarr
  - bazarr
  - plex
  - sabnzbd
  - sabnzbd-tv
  - overseerr
  - jellyfin
