apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
namespace: transmission
resources:
  - namespace.yaml
  - deployment.yaml
  - ingress.yaml
  - service.yaml
  - pvc.yml
  - config.pv.yaml
  - loadbalancer-tcp.yaml
  - loadbalancer-udp.yaml