apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  releaseName: home-assistant
  chart:
    spec:
      chart: home-assistant
      version: "14.0.1"
      sourceRef:
        kind: HelmRepository
        name: k8s-home-lab
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  values:
    env:
      PUID: "1001"
      PGID: "1001"
      TZ: "America/Edmonton"
    persistence:
      config:
        enabled: true
        accessMode: ReadWriteMany
        type: pvc
        storageClass: ""
        size: 10Gi
        selector:
          matchLabels:
            app: homeassistant
        # emptyDir:
        #   enabled: false
        # storageClass: "-"
        # size: 15Gi
    mariadb:
      enabled: true
      primary:
        persistence:
          enabled: true
          storageClass: freenas-iscsi-csi
