apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/ingress
  - service.yaml
  - endpoints.yaml
patches:
  - target:
      kind: IngressRoute
      name: ingress
    patch: |-
      - op: replace
        path: /metadata/name
        value: zwave2-ingress
      - op: replace
        path: /spec/routes/0/match
        value: Host(`zwave2.samsonnguyen.ca`)
      - op: add
        path: /spec/routes/0/services/0
        value: {"name": "zwave2", "port": 8091, "namespace": "zwave" }