apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plex
spec:
  releaseName: plex
  chart:
    spec:
      chart: plex
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      version: ~6.3
  interval: 5m
  values:
    env:
      PUID: "1001"
      PGID: "1001"
      TZ: "America/Edmonton"
    persistence:
      config:
        enabled: true
        accessMode: ReadWriteMany
        storageClass: openebs-jiva-csi-default
        type: pvc
        size: 15Gi
      shared:
        enabled: true
        accessMode: ReadWriteMany
        type: pvc
        storageClass: ""
        size: 8Ti
        selector:
          matchLabels:
            app: plex
      # transcode:
      #   enabled: true
      #   accessMode: ReadWriteOnce
      #   emptyDir:
      #     enabled: true
      #     medium: Memory
      #   mountPath: /transcode
      #   size: "6Gi"
    service:
      main:
        type: LoadBalancer