---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: grafana-ingress
spec:
  entryPoints:
    - websecure
  routes:
    - match:
      kind: Rule
      services:
        - name: kube-prometheus-stack-grafana
          port: 80
          namespace: prometheus
      middlewares:
      - name: traefik-sso@kubernetescrd
      - name: traefik-redirect-scheme@kubernetescrd
  tls:
    secretName: default-samsonnguyen-ca
