apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
namespace: prometheus
resources:
  - namespace.yaml
  - release.yaml
  - ../ingress
  - grafana-ingress-route.yaml
patches:
  - target:
      kind: IngressRoute
      name: ingress
    patch: |-
      - op: replace
        path: /metadata/name
        value: prometheus-ingress
  - target:
      kind: IngressRoute
      name: ingress
    path: prometheus-ingress-patch.yaml