apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
resources:
  - ../../base/graphite
patches:
  - target:
      kind: Service
      name: graphite-tcp
      namespace: graphite
    patch: |-
      - op: add
        path: /spec/loadBalancerIP
        value: 10.0.11.4