apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
namespace: traefik
resources:
  - ../../base/traefik-middleware
  - ../../base/traefik-sso
  - traefik-sso-ingress.yaml
patchesStrategicMerge:
  - traefik-sso-deployment-patch.yaml