apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sabnzbd
spec:
  releaseName: sabnzbd
  chart:
    spec:
      chart: sabnzbd
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  interval: 5m
  values:
    env:
      TZ: "America/Edmonton"
    persistence:
      config:
        enabled: true
        storageClass: openebs-jiva
        accessMode: ReadWriteMany
        type: pvc
        size: 15Gi
      shared:
        enabled: true
        accessMode: ReadWriteMany
        type: pvc
        storageClass: ""
        size: 8Ti
        selector:
          matchLabels:
            app: sabnzbd