name: e2e

on:
  push:
    branches-ignore:
      - 'main'
    tags-ignore:
      - '*'

jobs:
  kubernetes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup tools
        uses: ./.github/actions/tools
      - name: Setup Flux
        uses: fluxcd/flux2/action@main
      - name: Setup Kubernetes
        uses: engineerd/setup-kind@v0.5.0
      - name: Install Flux in Kubernetes Kind
        run: flux install
      - name: Setup cluster reconciliation
        run: |
          flux create source git flux-system \
          --url=${{ github.event.repository.html_url }} \
          --branch=${GITHUB_REF#refs/heads/}
          flux create kustomization flux-system \
          --source=flux-system \
          --path=./clusters/staging
      - name: Verify cluster reconciliation
        run: |
          kubectl -n flux-system wait kustomization/infrastructure --for=condition=ready --timeout=1m
          kubectl -n flux-system wait kustomization/apps --for=condition=ready --timeout=1m
      - name: Verify helm reconciliation
        run: |
          kubectl -n nginx wait helmrelease/nginx --for=condition=ready --timeout=1m
          kubectl -n redis wait helmrelease/redis --for=condition=ready --timeout=1m
      - name: Debug failure
        if: failure()
        run: |
          kubectl -n flux-system get all
          kubectl -n flux-system logs deploy/source-controller
          kubectl -n flux-system logs deploy/kustomize-controller
          kubectl -n flux-system logs deploy/helm-controller
