apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bazarr
spec:
  values:
    image:
      repository: ghcr.io/onedr0p/bazarr
      tag: rolling
      pullPolicy: Always
    podAnnotations:
      backup.velero.io/backup-volumes: config
