apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - plex-media-pv.yaml
  - radarr-media-pv.yaml
  - sonarr-media-pv.yaml
  - radarr-config-pv.yaml
  - sonarr-config-pv.yaml
  - ../../base/media
patches:
  - target:
      kind: IngressRoute
      name: node-red-ingress
      namespace: node-red
    path: ingressroute-patch.yaml