apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - plex-media-pv.yaml
  - radarr-media-pv.yaml
  - sonarr-media-pv.yaml
  - ../../base/media
patchesStrategicMerge:
  - plex-values.yaml
patches:
  - target:
      kind: IngressRoute
      name: plex-ingress
      namespace: media
    patch: |-
      - op: replace
        path: /spec/routes/0/match
        value: Host(`plex.samsonnguyen.ca`)
      - op: remove
        path: /spec/routes/0/middlewares/0
  - target:
      kind: IngressRoute
      name: sonarr-ingress
      namespace: media
    patch: |-
      - op: replace
        path: /spec/routes/0/match
        value: Host(`sonarr.samsonnguyen.ca`)
  - target:
      kind: IngressRoute
      name: radarr-ingress
      namespace: media
    patch: |-
      - op: replace
        path: /spec/routes/0/match
        value: Host(`radarr.samsonnguyen.ca`)
  - target:
      kind: IngressRoute
      name: sabnzbd-ingress
      namespace: media
    patch: |-
      - op: replace
        path: /spec/routes/0/match
        value: Host(`sabnzbd.samsonnguyen.ca`)