apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: overseerr
spec:
  values:
    podAnnotations:
      backup.velero.io/backup-volumes: config
    ingress:
      # -- Enable and configure ingress settings for the chart under this key.
      main:
        enabled: true
        hosts:
          - host: requests.samsonnnguyen.ca
            paths:
              - path: /
                pathType: Prefix
                service:
                  port: http
