apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-shared
  labels:
    app: plex
spec:
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 8Ti
  nfs:
    path: /mnt/media
    server: kube-worker2.samsonnguyen.ca
  volumeMode: Filesystem
