apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-media
spec:
  accessModes:
  - ReadWriteOnce
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: plex-media
    namespace: media
  nfs:
    path: /mnt/storage_1/movies
    server: freenas-int.samsonnguyen.ca
  volumeMode: Filesystem
