apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-media
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 8Ti
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: plex-media
    namespace: media
    size: 15Gi
  nfs:
    path: /mnt/storage_1/movies
    server: freenas-int.samsonnguyen.ca
  volumeMode: Filesystem
