apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-shared-tv
  labels:
    app: plex-tv
spec:
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 8Ti
  nfs:
    path: /mnt/media2
    server: kube-worker2.samsonnguyen.ca
  volumeMode: Filesystem
