apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plex
spec:
  values:
    image:
      tag: v1.23.2.4656-85f0adf5b
    env:
      PUID: "1001"
      PGID: "1001"
      TZ: "America/Edmonton"
      ALLOWED_NETWORKS: 10.0.0.0/8,192.168.0.0/24,plex.samsonnguyen.ca
      HOSTNAME: plex.samsonnguyen.ca
    envValueFrom:
      PLEX_CLAIM:
        secretKeyRef:
          name: plex-claim
          key: claim
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: 10.0.11.3
    podSecurityContext:
      runAsUser: 1001
      runAsGroup: 1001
      fsGroup: 1001
      # Hardware acceleration using an Intel iGPU w/ QuickSync
      # These IDs below should be matched to your `video` and `render` group on the host
      # To obtain those IDs run the following grep statement on the host:
      # $ cat /etc/group | grep "video\|render"
      # video:x:44:
      # render:x:109:
      supplementalGroups:
      - 998
      - 39
    resources:
      requests:
        # Hardware acceleration using an Intel iGPU w/ QuickSync and
        # using intel-gpu-plugin (https://github.com/intel/intel-device-plugins-for-kubernetes)
        nvidia.com/gpu: 1
        cpu: 400m
        memory: 1024Mi
      limits:
        # Hardware acceleration using an Intel iGPU w/ QuickSync and
        # using intel-gpu-plugin (https://github.com/intel/intel-device-plugins-for-kubernetes)
        nvidia.com/gpu: 1
        memory: 8192Mi
    podAnnotations:
      backup.velero.io/backup-volumes: config