apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-shared
  labels:
    app: plex
spec:
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 8Ti
  nfs:
    path: /mnt/storage_1/movies
    server: freenas-int.samsonnguyen.ca
  volumeMode: Filesystem