apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sabnzbd
spec:
  values:
    podAnnotations:
      backup.velero.io/backup-volumes: config
    environment:
      HOST_WHITELIST_ENTRIES: sanbzbd.samsonnguyen.ca
