apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sabnzbd-tv
spec:
  values:
    podAnnotations:
      backup.velero.io/backup-volumes: config
    env:
      HOST_WHITELIST_ENTRIES: sabnzbd-tv.samsonnguyen.ca
