apiVersion: v1
kind: PersistentVolume
metadata:
  finalizers:
  - kubernetes.io/pv-protection
  name: sonarr-media
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage:  8Ti
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: sonarr-media
    namespace: plex
  nfs:
    path: /mnt/storage_1/movies
    server: freenas-int.samsonnguyen.ca
  volumeMode: Filesystem
