apiVersion: v1
kind: PersistentVolume
metadata:
  finalizers:
  - kubernetes.io/pv-protection
  name: sonarr-config
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 15Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: sonarr-config
    namespace: media
  iscsi:
    fsType: ext4
    iqn: iqn.2018-10.lan.home:sonarr-config
    iscsiInterface: default
    lun: 0
    targetPortal: 10.0.10.10:3260
  volumeMode: Filesystem
